### PR TITLE
Bug fix int overflow file size >2G

### PR DESCRIPTION
**Pull request by Meeuwisse**
Signed-off-by: Michael Meeuwisse <mickeymeeuw+git@gmail.com>

### CODE REVIEW

**Comment by nyh** [comment]
Hi, I just committed your previous patch, which only changed the type of
the file size API.

This patch includes that patch, and other new stuff. Can you please send
the new stuff as a separate patch? And send it to the list, please, not as
a pull request?
Thanks. Nadav.


--
Nadav Har'El
nyh@scylladb.com

**Comment by nyh** [comment]
Hmm, I just noticed that I can actually take the parts of the patch from this pull request. So I'll try to do it now so you won't have to resend.

**Comment by nyh** [comment]
Sorry, I couldn't figure out how to conveniently extract patches from github. Moreover, I have some questions. So please send the patches to the mailing list. Thanks.

**Comment by Meeuwisse** [comment]
Thanks for committing the first one.

The remaining patches aren't ready for prime-time yet. I wasn't sure if you
could link the emailed patch to my github account, hence the additional
pull request. But I didn't realize the pull request would bring the
additional patches in the spotlight, my bad! I'll mail them in when I've
sorted out a few remaining edge cases.

**Pull request closed without merging**
