### PR TITLE
Read-only file system

### PR DESCRIPTION
**Pull request by jdroot**
I have implemented a read-only file system for OSv and integrated it into the build system (by using rootfs=mfs on scripts/build). This addition is a partial fix to issues discussed on [Issue 195](https://github.com/cloudius-systems/osv/issues/195). Discussion about the file system itself can be found on the [osv-dev mailing list](https://groups.google.com/forum/#!topic/osv-dev/dugTls17hkg).

Per the discussion on osv-dev, the code in this request generates the file system images with python instead of a host binary and the driver has a very simple LRU cache (set at 512kb).

### CODE REVIEW

**Comment by nyh** [comment]
Can you please send this patch to the mailing list, so it could be reviewed?

If you think this patch is too big for one patch, you can make it into a
patch series.

Thanks.

On Wed, Jul 29, 2015 at 6:18 PM, James Root <notifications@github.com>
wrote:

> I have implemented a read-only file system for OSv and integrated it into
> the build system (by using rootfs=mfs on scripts/build). This addition is a
> partial fix to issues discussed on Issue 195
> <https://github.com/cloudius-systems/osv/issues/195>. Discussion about
> the file system itself can be found on the osv-dev mailing list
> <https://groups.google.com/forum/#!topic/osv-dev/dugTls17hkg>.
>
> Per the discussion on osv-dev, the code in this request generates the file
> system images with python instead of a host binary and the driver has a
> very simple LRU cache (set at 512kb).
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/cloudius-systems/osv/pull/646
> Commit Summary
>
>    - Adding support for "MFS", which allows OSv to be built with a
>    read-only root file system using: script/build rootfs=mfs
>    - Added a simple 512kb cache to MFS to improve read performance
>    - Removed mkfs.mfs and replaced it with gen-mfs-img.py so we do not
>    need to compile anything on the host. The gen script also goes directly
>    from a manifest file to a mfs disk image, instead of copying to a directory
>    and building from there. The Makefile and build script have been updated to
>    use the new script
>    - Updated the cache semantics so it unlocks on an error (meaning you
>    don't need to call release). Also changed the sizes to be #defines
>
> File Changes
>
>    - *M* Makefile
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-0> (12)
>    - *A* fs/mfs/mfs.h
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-1> (113)
>    - *A* fs/mfs/mfs_cache.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-2> (133)
>    - *A* fs/mfs/mfs_cache.h
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-3> (113)
>    - *A* fs/mfs/mfs_inode.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-4> (94)
>    - *A* fs/mfs/mfs_vfsops.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-5> (139)
>    - *A* fs/mfs/mfs_vnops.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-6> (343)
>    - *M* fs/vfs/main.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-7> (12)
>    - *M* fs/vfs/vfs_conf.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-8> (3)
>    - *M* loader.cc
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-9> (12)
>    - *M* scripts/build
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-10> (60)
>    - *A* scripts/gen-mfs-img.py
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-11> (293)
>    - *M* scripts/run.py
>    <https://github.com/cloudius-systems/osv/pull/646/files#diff-12> (1)
>
> Patch Links:
>
>    - https://github.com/cloudius-systems/osv/pull/646.patch
>    - https://github.com/cloudius-systems/osv/pull/646.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cloudius-systems/osv/pull/646>.
>



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by jdroot** [comment]
Can do. This is my first time submitting a patch, do I send a [PATCH] message to the mailing list with the git format-patch output for each of my commits (and the signed off line)?

**Comment by nyh** [comment]
On Wed, Jul 29, 2015 at 6:44 PM, James Root <notifications@github.com>
wrote:

> Can do. This is my first time submitting a patch, do I send a [PATCH]
> message to the mailing list with the git format-patch output for each of my
> commits (and the signed off line)?
>

Yes, please. If you use "git commit -s" the sign-off line will be added
automatically to your commit message (or you can add it manually), you can
use git format-patch HEAD^ to format one commit as a patch, or git
format-patch HEAD^^^^ to format 4 patches (etc.),and you can use git
send-email to send the patch to the mailing list (various pages on the web
explain how to set it up properly if you don't have an MTA installed on
your own machine).
Or any other similar technique.

Just please to not add the patch as an "attachment" in the mail. We'd like
to see it as an integral part of the mail's text, so we can add comments to
it inline, and the other readers of the mailing list will see the whole
correspondence (compare this to github workflow, where only the submitter
and reviewer are aware of the review being done, and the others aren't even
aware that this is going on).


-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by copumpkin** [comment]
Did this make it to the mailing list and get merged? Kind of curious what the status is.

**Comment by dorlaor** [comment]
On Fri, Sep 11, 2015 at 8:19 PM, Daniel Peebles <notifications@github.com>
wrote:

> Did this make it to the mailing list and get merged? Kind of curious what
> the status is.
>

Have you followed Nadav's instructions to migrate the pull to a patch
series instructions?
We like to see it in as well

**Comment by copumpkin** [comment]
It's not my pull request, but maybe @jdroot did?

**Comment by jdroot** [comment]
Hey guys, I had submitted a patch in this
<https://groups.google.com/forum/#!searchin/osv-dev/readonly/osv-dev/DYSH4_NqyMg/YFJxM9NKBgAJ>
thread a while back. I was unsure if it was submitted properly or not
though. If not, I can validate that the patch is compatible with the
current build of OSv and re-submit the patch.

**Comment by copumpkin** [comment]
Ah, it looks like it's pending review then on the mailing list. Perhaps worth a ping to remind people it's there?

**Comment by dorlaor** [comment]
On Tue, Sep 15, 2015 at 10:04 PM, Daniel Peebles <notifications@github.com>
wrote:

> Ah, it looks like it's pending review then on the mailing list. Perhaps
> worth a ping to remind people it's there?
>

We're busy on top our heads with a release targeted for next week on a
holiday period. Apologize for the time it takes, please have some more
patient.
Dor

**Comment by nyh** [comment]
A new discussion on these patches and attempt to  get them in (and perform well):
https://groups.google.com/d/msg/osv-dev/ciocPasXTjE/VTV89p1JBwAJ

**Comment by geraldo-netto** [comment]
Dear @nyh / @wkozaczuk ,

I think we could close this ticket considering the ROFS @wkozaczuk has committed

Kind Regards,
Geraldo Netto

**Comment by wkozaczuk** [comment]
We have since implemented ROFS based on some ideas from series of patches sent by @jdroot so I am closing this pull request.

**Pull request closed without merging**
