### PR TITLE
fixed linuxmint 17.2

### PR DESCRIPTION
**Pull request by bretthartshorn**
scripts/setup.py now works on linuxmint

### CODE REVIEW

**Comment by nyh** [comment]
Thanks for the patch.  Justin Hendren also sent a similar patch a few days
ago, but that patch appeared to be corrupted, and I couldn't apply it.

In the OSv project, we do not use "Github pull requests" - rather we ask
that people send the patch to the mailing list (usually with something
like  "git format-patch HEAD^;  git send-email ..."). The benefit of
patches on the mailing list is that everyone can see them (not just a
link), and more important, see the review being done to them.

Additionally, you need to add a "Signed-off-by: Your Name
<your@email.address>" at the end of your commit message, which signifies
your awareness that you are contributing this code to a free software
project, and have the right to do so. This is explained in the
"CONTRIBUTING"  file in our source code.

Thanks,
Nadav.


--
Nadav Har'El
nyh@scylladb.com

**Comment by bretthartshorn** [comment]
@nyh 
did we just jump back in time to the 1990's? i'm not going to post any patches in the mailing list and i doubt many others will either.  The modern way of doing this is with github pull requests, its time to update your old-school policies.

**Comment by nyh** [comment]
I'm CCing to the mailing list because I'm sure other OSv would-be
developers would like to understand this issue:

On Wed, Dec 9, 2015 at 3:13 PM, brett hartshorn <notifications@github.com>
wrote:

> @nyh <https://github.com/nyh>
> did we just jump back in time to the 1990's?
>
i'm not going to post any patches in the mailing list and i doubt many
> others will either. The modern way of doing this is with github pull
> requests, its time to update your old-school policies.
>
github pull requests are not "the modern way" they are the github-only way,
when your entire development workflow revolves around the github web site
and nothing else.
I'm sure that Github would just love your sentiment that the only way to
send patches nowadays are through their site, but really, a whole world
exists outside of Github, and it is just one of many tools we all use daily.

In my previous mail I tried to explain the most basic problem with "pull
requests" which led us to our current "patches to the mailing list" policy:

With github pull requests, the review process is usually a one-on-one
exchange between the patch submitter, and the specific person who decided
to review it. While a review is going on, other people not directly
involved (not the author of the patch or the reviewer) will not be aware
that this review is going on, or what the review comments were.

On the other hand, sending patches to the mailing list "forces" all the
readers of the mailing list (who are, as the mailing list's name suggests,
OSv *developers*) to see all the patches, and all the reviews that happen.
Everyone has a much better chance of following the development, and we have
a better chance to get reviews and to learn from other people's reviews.

Finally, many other open-source projects use mailing lists and patches.

P.S. I can easily extract your patch from the pull request and apply it in
case I have no review comments. But, I still need the "Sign-off-by" line
(as explained in CONTRIBUTING). Unless you think this is 1990s as well ;-)

Nadav.

**Comment by bretthartshorn** [comment]
not sure if its any help here, but i do sign off that i am legally allowed to submit the patch, and agree with the license terms.

**Pull request closed without merging**
