### PR TITLE
Add fedora 37 support

### PR DESCRIPTION
**Pull request by benipeled**
This change is required for runners upgrade FC34 -> FC37

### CODE REVIEW

**Comment by benipeled** [comment]
Travis CI failed on docker operation (the last success CI was two years ago!)

Verified locally by running `./scripts/setup.py` on FC37 container

**Comment by wkozaczuk** [comment]
@benipeled It looks like maybe github does not have access to the docker token when running checks triggered by pull requests. I will investigate this. 

Most people send patches to the mailing list (see https://github.com/cloudius-systems/osv/wiki/Formatting-and-sending-patches). But we would want pull requests work as well.

BTW have you tried to run `./scripts/build check` on Fedora 37? Do all unit tests pass? The latest fedora we tried (but setup.py was not updated for that) was 36. Sometimes we need to tweak things to make a new gcc version that comes with the relevant version of Linux distribution to compile correctly.

**Comment by wkozaczuk** [comment]
Also, I am currently working on restoring access to our Travis CI integration as the integration token expired and the build is broken because of this. This obviously should not affect building locally.

**Review by nyh — APPROVED** [review]
Wow, I didn't realize we didn't have Fedora_36 either. I did build OSv on both Fedora 36 and 37, but I guess never tried to run the setup.py script...

**Comment by nyh** [comment]
Thanks. Committed (417887f87c3c542d781bdd2d6724d81a82fb5179) so closing PR.
We should also add Fedora 36 to the list, but I guess it's not critical now (you don't need it for your Jenkins runs).

**Comment by nyh** [comment]
> BTW have you tried to run `./scripts/build check` on Fedora 37? Do all unit tests pass? The latest fedora we tried (but setup.py was not updated for that) was 36. Sometimes we need to tweak things to make a new gcc version that comes with the relevant version of Linux distribution to compile correctly.

If I remember correctly I did test OSv on both Fedora 36 and Fedora 37 - I just didn't bother running setup.py because it didn't have anything new (and my system was upgraded incrementally, so I rand setup.py on it some time in the past, when it was Fedora 35 or earlier). I don't remember if I ran **all** the tests on Fedora 37, though. I guess now we'll know :-)

**Comment by benipeled** [comment]
> BTW have you tried to run ./scripts/build check on Fedora 37

nope, and it shame because this change broke the build (and we currently have no CI to catch it)

```shell
[root@34eabd9daade osv]# 
[root@34eabd9daade osv]# scripts/build -j4 image=cassandra
Building into build/release.x64
  GEN gen/include/osv/version.h
  GEN gen/include/osv/drivers_config.h
fatal: No names found, cannot describe anything.
No such image configuration: cassandra. Assuming list of modules.
Importing /osv/apps/cassandra/module.py
Importing /osv/modules/java/module.py
Importing /osv/modules/openjdk9_1x-from-host/module.py
/usr/bin/javac
No module.py in /osv/modules/ca-certificates
No module.py in /osv/modules/libz
Modules:
  ca-certificates
  libz
  openjdk9_1x-from-host
  java
  cassandra.*
make: *** [Makefile:19: module] Error 1
Traceback (most recent call last):
  File "/osv/scripts/module.py", line 283, in <module>
    args.func(args)
  File "/osv/scripts/module.py", line 236, in build
    make_modules(modules, args)
  File "/osv/scripts/module.py", line 127, in make_modules
    raise Exception('make failed for ' + module.name)
Exception: make failed for openjdk9_1x-from-host
scripts/build failed: ( for i in "${args[@]}";
do
    case $i in 
        *=*)
            export "$i"
        ;;
    esac;
done; export fs_type mode OSV_BUILD_PATH libgcc_s_dir; export ARCH=$arch OSV_BASE=$SRC; scripts/module.py $j_arg build -c "$modules" $usrskel_arg $no_required_arg )
```

It raise on `modules/java/module.py`
```python
if javac_with_version.startswith('javac 1.8'):
    api.require('java-non-isolated')
    api.require('openjdk8-from-host')
else:
    api.require('openjdk9_1x-from-host')
```
the javac version on FC34 (at least on my env) is 17.0.5 hence the failure

**Pull request closed without merging**
